// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXvavHHstIIK_LXyKn1kTShzqxOIZlQ0',
    appId: '1:1031658583493:web:7268d65226c23425e207ac',
    messagingSenderId: '1031658583493',
    projectId: 'traveltribe-a2f84',
    authDomain: 'traveltribe-a2f84.firebaseapp.com',
    storageBucket: 'traveltribe-a2f84.appspot.com',
    measurementId: 'G-NR7WZ2C49J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdTJD0MGDH5zN38YBgbR1Z8so9FNbYxgU',
    appId: '1:1031658583493:android:208461a4835a719ce207ac',
    messagingSenderId: '1031658583493',
    projectId: 'traveltribe-a2f84',
    storageBucket: 'traveltribe-a2f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQVIZxqLCY4vgvPTdOeiQT3x4ZimTM80',
    appId: '1:1031658583493:ios:98288e8093933ff5e207ac',
    messagingSenderId: '1031658583493',
    projectId: 'traveltribe-a2f84',
    storageBucket: 'traveltribe-a2f84.appspot.com',
    iosBundleId: 'com.example.traveltribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQVIZxqLCY4vgvPTdOeiQT3x4ZimTM80',
    appId: '1:1031658583493:ios:98288e8093933ff5e207ac',
    messagingSenderId: '1031658583493',
    projectId: 'traveltribe-a2f84',
    storageBucket: 'traveltribe-a2f84.appspot.com',
    iosBundleId: 'com.example.traveltribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKXvavHHstIIK_LXyKn1kTShzqxOIZlQ0',
    appId: '1:1031658583493:web:1cd3279c852bbab0e207ac',
    messagingSenderId: '1031658583493',
    projectId: 'traveltribe-a2f84',
    authDomain: 'traveltribe-a2f84.firebaseapp.com',
    storageBucket: 'traveltribe-a2f84.appspot.com',
    measurementId: 'G-X6K5H6GM3X',
  );
}
